"""Task 1.0 — the characterization oracle for the register-registry refactor.

Captured from main (4a75500) BEFORE pipeline/registers.py existed. These
frozen literals are the byte-identical invariant that proves the registry
refactor changed nothing for the six existing registers: the exact plate
prompt (both pose-ref arms), the prop-path bypass, the model routing (base
+ manifest per-character override precedence), and the composed NB2 cache
key (with and without a reject_reason) that actually protects the locked
sean-anchor / claude-mascot Bibles.

If any assertion here ever fails, a locked Bible's plate cache would be
invalidated or re-authored differently — treat as a release blocker, never
"update the literal to match".

Expected values generated by a capture script run against main; do not
hand-edit them. Plan: docs/active/
2026-07-03-animation-vocabulary-expansion-execution-CONVERGED.md §5 Task 1.0.
"""

from __future__ import annotations

import pytest

from pipeline.agents.character_designer import (
    _build_plate_prompt,
    _resolve_plate_model,
)
from pipeline.agents.nb_pro_runner import _compute_cache_key

_SIX = [
    "pencil-test-colored",
    "pixel-art-8bit",
    "line-art-only",
    "watercolor",
    "photoreal",
    "3d-rendered",
]

_INTENT = "neutral standing pose"
_REF_BYTES = b"anima-oracle-fixed-reference-bytes-v1"
_CITES = ("IR.oracle.face.two-dot-eyes", "IR.oracle.palette.base")

# ---------------------------------------------------------------------------
# Frozen literals captured from main (4a75500). Do not hand-edit.
# ---------------------------------------------------------------------------

_EXPECTED_PROMPT = {
    ('pencil-test-colored', True): 'Image 1 is the identity anchor — the canonical reference for this character. Image 2 is the angle/pose target — match its viewing angle and pose, but the identity always comes from Image 1. Match the face, hair, full color palette, skin tone, and proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Keep the warm cream paper, the cross-hatch shadow, and the full color of Image 1. Do not render the figure in monochrome. No photographic shading. Do not add any text, captions, labels, annotations, or watermarks to the image. Warm pencil-test render: graphite line (not vector black), flat color fills, cross-hatch shadow, warm cream paper, hole-punch production marks. The character must stay recognizably identical to Image 1.',
    ('pencil-test-colored', False): 'Image 1 is the identity anchor — the canonical reference for this character. Match the face, hair, full color palette, skin tone, and proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Keep the warm cream paper, the cross-hatch shadow, and the full color of Image 1. Do not render the figure in monochrome. No photographic shading. Do not add any text, captions, labels, annotations, or watermarks to the image. Warm pencil-test render: graphite line (not vector black), flat color fills, cross-hatch shadow, warm cream paper, hole-punch production marks. The character must stay recognizably identical to Image 1.',
    ('pixel-art-8bit', True): 'Image 1 is the identity anchor — the canonical reference for this character. Image 2 is the angle/pose target — match its viewing angle and pose, but the identity always comes from Image 1. Match the indexed palette, the round silhouette, and the head-to-body ratio of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Hard pixel edges. No smooth anti-aliased gradients. Do not add any text, captions, labels, annotations, or watermarks to the image. 16-bit pixel-art sprite, limited indexed palette, hard pixel edges, clean outlines. The character must stay recognizably identical to Image 1.',
    ('pixel-art-8bit', False): 'Image 1 is the identity anchor — the canonical reference for this character. Match the indexed palette, the round silhouette, and the head-to-body ratio of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Hard pixel edges. No smooth anti-aliased gradients. Do not add any text, captions, labels, annotations, or watermarks to the image. 16-bit pixel-art sprite, limited indexed palette, hard pixel edges, clean outlines. The character must stay recognizably identical to Image 1.',
    ('line-art-only', True): 'Image 1 is the identity anchor — the canonical reference for this character. Image 2 is the angle/pose target — match its viewing angle and pose, but the identity always comes from Image 1. Match the contour shapes, line weight, hair silhouette, and proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. No shading, no gradients, no soft shadow, no texture; flat color fills only. Do not add any text, captions, labels, annotations, or watermarks to the image. Clean line art, bold uniform outlines, flat fills. The character must stay recognizably identical to Image 1.',
    ('line-art-only', False): 'Image 1 is the identity anchor — the canonical reference for this character. Match the contour shapes, line weight, hair silhouette, and proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. No shading, no gradients, no soft shadow, no texture; flat color fills only. Do not add any text, captions, labels, annotations, or watermarks to the image. Clean line art, bold uniform outlines, flat fills. The character must stay recognizably identical to Image 1.',
    ('watercolor', True): 'Image 1 is the identity anchor — the canonical reference for this character. Image 2 is the angle/pose target — match its viewing angle and pose, but the identity always comes from Image 1. Match the face, the pigment-pool palette, and the proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Keep the paper grain; let washes bleed; no hard vector edges. Do not add any text, captions, labels, annotations, or watermarks to the image. Soft watercolor wash, pigment-pool bleed, visible paper grain. The character must stay recognizably identical to Image 1.',
    ('watercolor', False): 'Image 1 is the identity anchor — the canonical reference for this character. Match the face, the pigment-pool palette, and the proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Keep the paper grain; let washes bleed; no hard vector edges. Do not add any text, captions, labels, annotations, or watermarks to the image. Soft watercolor wash, pigment-pool bleed, visible paper grain. The character must stay recognizably identical to Image 1.',
    ('photoreal', True): 'Image 1 is the identity anchor — the canonical reference for this character. Image 2 is the angle/pose target — match its viewing angle and pose, but the identity always comes from Image 1. Match the face, skin tone, hair, and proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Keep the lighting direction and color temperature of Image 1; clean edges, no halos. Do not add any text, captions, labels, annotations, or watermarks to the image. Photographic rendering, natural lighting, shallow depth of field. The character must stay recognizably identical to Image 1.',
    ('photoreal', False): 'Image 1 is the identity anchor — the canonical reference for this character. Match the face, skin tone, hair, and proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Keep the lighting direction and color temperature of Image 1; clean edges, no halos. Do not add any text, captions, labels, annotations, or watermarks to the image. Photographic rendering, natural lighting, shallow depth of field. The character must stay recognizably identical to Image 1.',
    ('3d-rendered', True): 'Image 1 is the identity anchor — the canonical reference for this character. Image 2 is the angle/pose target — match its viewing angle and pose, but the identity always comes from Image 1. Match the face, material palette, and proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Keep soft global illumination; no flat-shading artifacts. Do not add any text, captions, labels, annotations, or watermarks to the image. 3D-rendered look, soft global illumination, subtle ambient occlusion. The character must stay recognizably identical to Image 1.',
    ('3d-rendered', False): 'Image 1 is the identity anchor — the canonical reference for this character. Match the face, material palette, and proportions of Image 1 exactly. Render: neutral standing pose. Change only what this names; keep everything else exactly as in Image 1. Keep soft global illumination; no flat-shading artifacts. Do not add any text, captions, labels, annotations, or watermarks to the image. 3D-rendered look, soft global illumination, subtle ambient occlusion. The character must stay recognizably identical to Image 1.',
}

_EXPECTED_PROP_PROMPT = 'Render ONLY the isolated object described below, centered on a warm cream paper background. Do NOT draw any person, character, hand, body, or figure. Do NOT render any text, caption, label, handwriting, or annotation anywhere in the image. Render: neutral standing pose.'

# GA repin 2026-07-13 (decision D3 rider) — deliberate routing + cache-key
# oracle update; _SIX and clauses untouched.
_EXPECTED_ROUTING = {
    'pencil-test-colored': (('gemini-3.1-flash-image', 'gemini-3.1-flash-image'), ('X', 'Y')),
    'pixel-art-8bit': (('gemini-3.1-flash-image', 'gemini-3.1-flash-image'), ('X', 'Y')),
    'line-art-only': (('gemini-3.1-flash-image', 'gemini-3.1-flash-image'), ('X', 'Y')),
    'watercolor': (('gemini-3.1-flash-image', 'gemini-3-pro-image'), ('X', 'Y')),
    'photoreal': (('gemini-3.1-flash-image', 'gemini-3-pro-image'), ('X', 'Y')),
    '3d-rendered': (('gemini-3.1-flash-image', 'gemini-3-pro-image'), ('X', 'Y')),
}

_EXPECTED_CACHE_KEY = {
    'pencil-test-colored': ('fc0904ed51a476fc7a0f74d1f8b9a2cc286735988a680258fb751d8d1488b015', '9dc9d79d90d5f6b58d28112475b337a74862be7ebd6314984329fc57138cbc82'),
    'pixel-art-8bit': ('335055bc2edbba7504136be57dd65132e28ab53135662fd4f16b9eadf68b1f1c', '0b8687c28ff72fa2da09079216b307487ddaa7b74ae4cf333984ea0f50f40e44'),
    'line-art-only': ('0541f7901f977372a5050d1a50ede918eec12c77bccdc31d824a9da004b071f3', 'cca69989a514ce43fbced936c02007acdd91c9dc7875837fdb55d27457058034'),
    'watercolor': ('22d96a0982486b4c6f74fce9a7dfe2e6c59e41f35217daa14839a28cf9366561', 'cc4e89c72fbbec31a40d3fa5f7d1e85ed8e726f07768b562c15d00efc39bfa2f'),
    'photoreal': ('5ccf3f46b6279636cec3a486197303fa19a65d1464b101c359857e37a2e2a78f', 'f89fc3657cc2f719bb57ebaa82466e65b17cb29afe44ce6a2ae0f32bf2152d8b'),
    '3d-rendered': ('38246cf7742d5a9d2581c2208b25968d9134232089d94345fb2614644bf31119', '0eef683b772bc5d827e42b244fa7584a2c924e52fe3d7d64ff39d44a0d539367'),
}


# ---------------------------------------------------------------------------
# The oracle assertions
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("has_pose_ref", [True, False])
@pytest.mark.parametrize("reg", _SIX)
def test_plate_prompt_snapshot(reg, has_pose_ref):
    got = _build_plate_prompt(
        _INTENT, style_register=reg, has_pose_ref=has_pose_ref, is_prop=False
    )
    assert got == _EXPECTED_PROMPT[(reg, has_pose_ref)]


@pytest.mark.parametrize("has_pose_ref", [True, False])
@pytest.mark.parametrize("reg", _SIX)
def test_prop_path_snapshot(reg, has_pose_ref):
    """The prop plate bypasses register lookup entirely (character_designer
    ~L1288): identical output for every register/pose combination."""
    got = _build_plate_prompt(
        _INTENT, style_register=reg, has_pose_ref=has_pose_ref, is_prop=True
    )
    assert got == _EXPECTED_PROP_PROMPT


@pytest.mark.parametrize("reg", _SIX)
def test_model_routing_snapshot(reg):
    """Base routing (generation + final) AND manifest per-character override
    precedence — the override must keep winning after the refactor."""
    base = (
        _resolve_plate_model(reg, {}, final=False),
        _resolve_plate_model(reg, {}, final=True),
    )
    override = (
        _resolve_plate_model(
            reg, {"generation_model": "X", "final_model": "Y"}, final=False
        ),
        _resolve_plate_model(
            reg, {"generation_model": "X", "final_model": "Y"}, final=True
        ),
    )
    assert (base, override) == _EXPECTED_ROUTING[reg]


@pytest.mark.parametrize(
    ("character_id", "expected"),
    [
        # one per keyword in _STUB_STYLE_REGISTER_BY_KEYWORD
        ("claude-mascot", "pixel-art-8bit"),
        ("pixel-knight", "pixel-art-8bit"),
        ("watercolor-fox", "watercolor"),
        ("lineart-hero", "line-art-only"),
        ("photoreal-anna", "photoreal"),
        ("3d-bot", "3d-rendered"),
        # no keyword hit -> pencil default
        ("sean-anchor", "pencil-test-colored"),
        # keyword-precedence edges: insertion order of the keyword map wins
        # (mascot before pixel; watercolor before lineart). The registry
        # derivation must reproduce this ordering exactly.
        ("watercolor-mascot", "pixel-art-8bit"),
        ("watercolor-lineart-test", "watercolor"),
    ],
)
def test_stub_register_inference_snapshot(character_id, expected):
    from pipeline.agents.character_designer import _infer_stub_style_register

    assert _infer_stub_style_register(character_id) == expected


def test_reject_threaded_prompt_snapshot():
    """Verifier-flagged gap: the reject_reason clause threads into the
    preserve slot; snapshot the full composed prompt so a regression in that
    clause trips the oracle, not just the cache key. (Literal verified
    hash-identical to main's output across all registers/pose arms by the
    fresh-context Checkpoint-1 verifier.)"""
    got = _build_plate_prompt(
        _INTENT,
        style_register="pencil-test-colored",
        has_pose_ref=False,
        reject_reason="eyes too large",
    )
    assert got == (
        'Image 1 is the identity anchor — the canonical reference for this '
        'character. Match the face, hair, full color palette, skin tone, and '
        'proportions of Image 1 exactly. Render: neutral standing pose. '
        'Change only what this names; keep everything else exactly as in '
        'Image 1. Keep the warm cream paper, the cross-hatch shadow, and the '
        'full color of Image 1. Do not render the figure in monochrome. No '
        'photographic shading. Do not add any text, captions, labels, '
        'annotations, or watermarks to the image. Correction from the '
        'previous attempt — address this and do not repeat it: eyes too '
        'large Warm pencil-test render: graphite line (not vector black), '
        'flat color fills, cross-hatch shadow, warm cream paper, hole-punch '
        'production marks. The character must stay recognizably identical '
        'to Image 1.'
    )


def test_stub_keyword_map_full_order_snapshot():
    """Verifier-flagged gap: the stub keyword map's precedence rides on dict
    insertion order. Pin the ENTIRE key order + mapping (not just the two
    precedence edges) so reordering REGISTRY entries fails loud here.

    The first SIX entries are the frozen pre-registry order — never reorder
    or interleave them. A NEW register's keywords append strictly AFTER
    (primal-sketch-grit, Checkpoint 2, is the pattern): appended-last keeps
    every pre-registry character id resolving exactly as before."""
    from pipeline.agents.character_designer import _STUB_STYLE_REGISTER_BY_KEYWORD

    assert list(_STUB_STYLE_REGISTER_BY_KEYWORD.items()) == [
        # frozen pre-registry prefix (main 4a75500 behavior) —
        ("mascot", "pixel-art-8bit"),
        ("pixel", "pixel-art-8bit"),
        ("watercolor", "watercolor"),
        ("lineart", "line-art-only"),
        ("photoreal", "photoreal"),
        ("3d", "3d-rendered"),
        # — post-registry registers append below, never above.
        ("primal", "primal-sketch-grit"),
        ("nicktoon", "90s-nicktoon-grossout"),
        ("grossout", "90s-nicktoon-grossout"),
        ("samurai", "samurai-jack-s5"),
        ("fusion", "flat-cast-painted-world"),
    ]


@pytest.mark.parametrize("reg", _SIX)
def test_cache_key_snapshot(reg, tmp_path):
    """The composed NB2 cache key is what actually protects the locked
    Bibles (nb_pro_runner._compute_cache_key): prompt + model + sorted rule
    cites + reject + reference content hashes. Snapshot with and without a
    reject_reason for a representative plate per register."""
    ref = tmp_path / "anchor.png"
    ref.write_bytes(_REF_BYTES)
    prompt = _build_plate_prompt(
        _INTENT, style_register=reg, has_pose_ref=False, is_prop=False
    )
    model = _resolve_plate_model(reg, {}, final=False)
    key = _compute_cache_key(
        prompt=prompt,
        reference_images=[ref],
        cites_identity_rules=_CITES,
        reject_reason=None,
        model=model,
    )
    key_rej = _compute_cache_key(
        prompt=prompt,
        reference_images=[ref],
        cites_identity_rules=_CITES,
        reject_reason="eyes too large",
        model=model,
    )
    assert (key, key_rej) == _EXPECTED_CACHE_KEY[reg]
